project:
  type: website
  output-dir: docs

website:
  title: "Team Let It Happen"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data"
        href: data.qmd
      - text: "Analysis"
        href: analysis.qmd
    right:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2024-team-letithappen

format:
  html:
    theme: slate       # Analysis sayfasında beğendiğin o modern koyu ton budur.
    css: styles.css    # Özel cam kart efektlerin için.
    code-fold: true
    toc: true
    toc-title: "İçerik"
    smooth-scroll: true