project:
  type: website
  output-dir: docs

website:
  title: "Team Let It Happen"
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data"
        href: data.qmd
      - text: "Analysis"
        href: analysis.qmd

format:
  html:
    theme: cosmo
    code-fold: true      # Hocanın kuralı: Kodlar katlanabilir olmalı!
    code-tools: true
    toc: true